# Generated by Django 4.0.5 on 2022-06-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0007_remove_batch_variety_delete_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Location Name Not Set', max_length=50)),
                ('sub_name', models.CharField(blank=True, default='Additional Name Not Set', max_length=50, null=True)),
                ('address_line1', models.CharField(default='Address Not Set', max_length=45)),
                ('address_line2', models.CharField(blank=True, max_length=45)),
                ('postal_code', models.CharField(default='ZIPCode Not Set', max_length=15)),
                ('city', models.CharField(default='City Not Set', max_length=50)),
                ('state_province', models.CharField(default='State Not Set', max_length=40)),
                ('country', models.CharField(default='USA', max_length=40)),
                ('corporate', models.BooleanField(null=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='17042123123', max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'unique_together': {('address_line1', 'address_line2', 'postal_code', 'city', 'state_province', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.ManyToManyField(related_name='retail_locations', to='supplies.location')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply', to='supplies.retailer')),
                ('volume_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply', to='batch.volumeunit')),
                ('weight_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply', to='batch.weightunit')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('supply_list', models.ManyToManyField(related_name='season', to='supplies.supply')),
            ],
        ),
    ]
