# Generated by Django 4.0.5 on 2022-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='supply_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='season', to='supplies.supply'),
        ),
    ]
