# Generated by Django 4.0.5 on 2022-06-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_remove_batch_variety_delete_variety'),
        ('supplies', '0002_alter_season_supply_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'Supplies'},
        ),
        migrations.AlterField(
            model_name='supply',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply', to='supplies.retailer'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='volume_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply', to='batch.volumeunit'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='weight_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply', to='batch.weightunit'),
        ),
    ]
