# Generated by Django 4.0.5 on 2022-06-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_supply_options_alter_supply_retailer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'address_line1', 'address_line2', 'postal_code', 'city', 'state_province', 'country')},
        ),
    ]
