# Generated by Django 4.0.5 on 2022-06-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='supply_list',
            field=models.ManyToManyField(blank=True, related_name='season', to='supplies.supply'),
        ),
    ]
