# Generated by Django 4.0.5 on 2022-06-20 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('phone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(default='1', max_length=1)),
                ('area_code', models.CharField(blank=True, max_length=3, null=True)),
                ('pnumber', models.CharField(blank=True, max_length=7, null=True)),
                ('extension', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='process', to='batch.batch')),
                ('steps', models.ManyToManyField(to='batch.step')),
            ],
        ),
    ]
