# Generated by Django 4.0.5 on 2022-06-20 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_consumer_alter_batch_options_alter_step_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('volume_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='batch.consumer')),
                ('volume_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='batch.volumeunit')),
            ],
        ),
    ]
