# Generated by Django 4.0.5 on 2022-06-20 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='ingredient',
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.ManyToManyField(to='batch.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch', to='batch.recipe'),
            preserve_default=False,
        ),
    ]
