# Generated by Django 4.0.5 on 2022-06-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_process_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
