# Generated by Django 4.0.5 on 2022-06-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_recipe_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='variety',
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
    ]
