# Generated by Django 4.0.5 on 2022-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_remove_batch_variety_delete_variety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(blank=True, default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
