# Generated by Django 4.0.5 on 2022-06-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_alter_process_options_alter_batch_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='process',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='process',
            name='steps',
        ),
    ]
