# Generated by Django 4.0.5 on 2022-06-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0010_process_steps_step_batch_step_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='name',
        ),
    ]
