# Generated by Django 4.0.5 on 2022-06-23 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0011_basicstep_remove_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='step', to='batch.basicstep'),
        ),
    ]
