# Generated by Django 4.0.5 on 2022-06-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0012_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='steps',
            field=models.ManyToManyField(through='batch.Step', to='batch.batch'),
        ),
    ]
