branch-defaults:
  default:
    environment: django-passata-env
    group_suffix: null
global:
  application_name: eb-django-passata
  branch: null
  default_ec2_keyname: eb-django-passata-keypair
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
